name: Build and Deploy Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test: # Renamed from 'job1' for clarity
    environment: testing
    runs-on: ubuntu-latest
    
    # Passing secrets to the job context
    env:
      DATABASE_HOSTNAME: ${{DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{DATABASE_PORT}}
      DATABASE_NAME: ${{DATABASE_NAME}}
      DATABASE_USERNAME: ${{DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{DATABASE_PASSWORD}}
      SECRET_KEY: ${{SECRET_KEY}}
      ALGORITHM: ${{ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ACCESS_TOKEN_EXPIRE_MINUTES}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip' # Helper to cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # Installing pytest here if not in requirements.txt

      - name: Run Tests
        run: |
           pip install pytest
           pytest -v -s